# Site settings
title: jessie willms
email: willms.jessie@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  jessie willms is a web developer, designer & digital storyteller. currently: digital designer, the toronto star.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jessiewill.com" # the base hostname & protocol for your site
twitter_username: jessiewillms
github_username:  jessiewillms

# Build settings
markdown: kramdown
